[NotebookApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] Serving notebooks from local directory: /home/ucsddse230/work
[NotebookApp | INFO] 0 active kernels
[NotebookApp | INFO] The Jupyter Notebook is running at:
[NotebookApp | INFO] http://[all ip addresses on your system]:8888/
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | INFO] interrupted
[NotebookApp | INFO] interrupted
[NotebookApp | CRITICAL] Shutdown confirmed
[NotebookApp | INFO] Shutting down 0 kernels
[NotebookApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] Serving notebooks from local directory: /home/ucsddse230/work
[NotebookApp | INFO] 0 active kernels
[NotebookApp | INFO] The Jupyter Notebook is running at:
[NotebookApp | INFO] http://[all ip addresses on your system]:8888/
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | INFO] 302 GET / (172.17.0.1) 28.28ms
[NotebookApp | INFO] Creating new notebook in 
[NotebookApp | INFO] Writing notebook-signing key to /home/ucsddse230/.local/share/jupyter/notebook_secret
[NotebookApp | INFO] Kernel started: dc5af8c5-90dc-40de-9ab2-08498cf532f3
[NotebookApp | WARNING] 404 GET /static/components/bootstrap/js/tooltip.js?v=20230201201236 (172.17.0.1) 108.72ms referer=http://localhost:8889/notebooks/Untitled.ipynb?kernel_name=python3
[NotebookApp | WARNING] Timeout waiting for kernel_info reply from dc5af8c5-90dc-40de-9ab2-08498cf532f3
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel dc5af8c5-90dc-40de-9ab2-08498cf532f3
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Starting buffering for dc5af8c5-90dc-40de-9ab2-08498cf532f3:1223c01c535a4e09841d174af41cd845
[NotebookApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] Serving notebooks from local directory: /home/ucsddse230/work
[NotebookApp | INFO] 0 active kernels
[NotebookApp | INFO] The Jupyter Notebook is running at:
[NotebookApp | INFO] http://[all ip addresses on your system]:8888/
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | INFO] 302 GET / (172.17.0.1) 1.56ms
[NotebookApp | INFO] 302 GET / (172.17.0.1) 2.16ms
[NotebookApp | INFO] interrupted
[NotebookApp | INFO] interrupted
[NotebookApp | CRITICAL] Shutdown confirmed
[NotebookApp | INFO] Shutting down 0 kernels
[NotebookApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] Serving notebooks from local directory: /home/ucsddse230/work
[NotebookApp | INFO] 0 active kernels
[NotebookApp | INFO] The Jupyter Notebook is running at:
[NotebookApp | INFO] http://[all ip addresses on your system]:8888/
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | INFO] 302 GET / (172.17.0.1) 2.25ms
[NotebookApp | INFO] Writing notebook-signing key to /home/ucsddse230/.local/share/jupyter/notebook_secret
[NotebookApp | WARNING] Notebook Test Jupyter Notebook.ipynb is not trusted
[NotebookApp | INFO] Kernel started: a4ad7724-4684-4218-8d12-3de69054a83f
[NotebookApp | WARNING] 404 GET /static/components/bootstrap/js/tooltip.js?v=20230201210718 (172.17.0.1) 76.17ms referer=http://localhost:8889/notebooks/Test%20Jupyter%20Notebook.ipynb
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel a4ad7724-4684-4218-8d12-3de69054a83f
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | INFO] Validating '/home/ucsddse230/work/Test Jupyter Notebook.ipynb'
[NotebookApp | INFO] Executing notebook with kernel: python3
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Starting buffering for a4ad7724-4684-4218-8d12-3de69054a83f:457e8e70bd1c49748ad49be167517998
[NotebookApp | INFO] Kernel restarted: a4ad7724-4684-4218-8d12-3de69054a83f
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel a4ad7724-4684-4218-8d12-3de69054a83f
[NotebookApp | INFO] Restoring connection for a4ad7724-4684-4218-8d12-3de69054a83f:457e8e70bd1c49748ad49be167517998
[NotebookApp | INFO] Replaying 5 buffered messages
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Copying Test Jupyter Notebook.ipynb to 
[NotebookApp | INFO] Kernel started: 8c280243-2f9d-4927-84c4-e7b6e0a39dd4
[NotebookApp | WARNING] 404 GET /static/components/bootstrap/js/tooltip.js?v=20230201210718 (172.17.0.1) 16.79ms referer=http://localhost:8889/notebooks/Test%20Jupyter%20Notebook-Copy1.ipynb
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel 8c280243-2f9d-4927-84c4-e7b6e0a39dd4
[NotebookApp | INFO] Creating new directory in 
[NotebookApp | CRITICAL] Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
[NotebookApp | CRITICAL] Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
[NotebookApp | CRITICAL] Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
[NotebookApp | CRITICAL] Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
[NotebookApp | WARNING] No nbgrader_config.py file found. Rerun with DEBUG log level to see where nbgrader is looking.
[NotebookApp | CRITICAL] Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
[NotebookApp | ERROR] Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/nbgrader/server_extensions/assignment_list/handlers.py", line 65, in list_released_assignments
        assignments = lister.start()
      File "/opt/conda/lib/python3.6/site-packages/nbgrader/exchange/list.py", line 129, in start
        super(ExchangeList, self).start()
      File "/opt/conda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 122, in start
        self.ensure_root()
      File "/opt/conda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 100, in ensure_root
        self.fail("Unwritable directory, please contact your instructor: {}".format(self.root))
      File "/opt/conda/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 78, in fail
        raise ExchangeError(msg)
    nbgrader.exchange.exchange.ExchangeError: Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
    
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook-Copy1.ipynb
[NotebookApp | INFO] 200 GET /tensorboard/1/ (172.17.0.1) 27.29ms
[NotebookApp | WARNING] 404 GET /font-roboto/oMMgfZMQthOryQo9n22dcuvvDin1pK8aKteLpeZ5c0A.woff2 (172.17.0.1) 3.47ms referer=http://localhost:8889/tensorboard/1/
[NotebookApp | INFO] 200 GET /tensorboard/1/data/runs (172.17.0.1) 3.13ms
[NotebookApp | INFO] 200 GET /tensorboard/1/data/environment (172.17.0.1) 9.56ms
[NotebookApp | INFO] 200 GET /tensorboard/1/data/plugins_listing (172.17.0.1) 11.75ms
[NotebookApp | INFO] 200 GET /tensorboard/1/data/environment (172.17.0.1) 2.63ms
[NotebookApp | INFO] 200 GET /tensorboard/1/data/plugins_listing (172.17.0.1) 33.62ms
[NotebookApp | WARNING] 404 GET /font-roboto/RxZJdnzeo3R5zSexge8UUZBw1xU1rKptJj_0jans920.woff2 (172.17.0.1) 13.94ms referer=http://localhost:8889/tensorboard/1/
[NotebookApp | INFO] 200 GET /tensorboard/1/data/runs (172.17.0.1) 2.20ms
[NotebookApp | WARNING] 404 GET /font-roboto/d-6IYplOFocCacKzxwXSOJBw1xU1rKptJj_0jans920.woff2 (172.17.0.1) 3.88ms referer=http://localhost:8889/tensorboard/1/
[NotebookApp | WARNING] 404 GET /font-roboto/vPcynSL0qHq_6dX7lKVByXYhjbSpvc47ee6xR_80Hnw.woff2 (172.17.0.1) 3.32ms referer=http://localhost:8889/tensorboard/1/
[NotebookApp | INFO] Creating new notebook in /Hello
[NotebookApp | INFO] Kernel started: 1a029dde-0b35-4ed2-af77-a019a54b5e0b
[NotebookApp | WARNING] 404 GET /static/components/bootstrap/js/tooltip.js?v=20230201210718 (172.17.0.1) 4.04ms referer=http://localhost:8889/notebooks/Hello/Untitled.ipynb?kernel_name=python3
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel 1a029dde-0b35-4ed2-af77-a019a54b5e0b
[NotebookApp | INFO] Kernel shutdown: 8c280243-2f9d-4927-84c4-e7b6e0a39dd4
[NotebookApp | WARNING] delete /Test Jupyter Notebook-Copy1.ipynb
[NotebookApp | WARNING] delete /Hello
[NotebookApp | INFO] Kernel shutdown: 1a029dde-0b35-4ed2-af77-a019a54b5e0b
[NotebookApp | INFO] Kernel shutdown: a4ad7724-4684-4218-8d12-3de69054a83f
[NotebookApp | WARNING] 404 GET /api/contents/Hello/Untitled.ipynb?content=0&_=1675287230527 (172.17.0.1): No such file or directory: Hello/Untitled.ipynb
[NotebookApp | WARNING] No such file or directory: Hello/Untitled.ipynb
[NotebookApp | WARNING] 404 GET /api/contents/Hello/Untitled.ipynb?content=0&_=1675287230527 (172.17.0.1) 4.11ms referer=http://localhost:8889/notebooks/Hello/Untitled.ipynb?kernel_name=python3
[NotebookApp | INFO] Uploading file to /Hello/Untitled.ipynb
[NotebookApp | ERROR] Error while saving file: Hello/Untitled.ipynb [Errno 2] No such file or directory: '/home/ucsddse230/work/Hello/Untitled.ipynb'
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 456, in save
        self._save_notebook(os_path, nb)
      File "/opt/conda/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 293, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/opt/conda/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/opt/conda/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 213, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/opt/conda/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/opt/conda/lib/python3.6/site-packages/notebook/services/contents/fileio.py", line 108, in atomic_writing
        fileobj = io.open(path, 'w', encoding=encoding, **kwargs)
    FileNotFoundError: [Errno 2] No such file or directory: '/home/ucsddse230/work/Hello/Untitled.ipynb'
[NotebookApp | WARNING] 500 PUT /api/contents/Hello/Untitled.ipynb (172.17.0.1): Unexpected error while saving file: Hello/Untitled.ipynb [Errno 2] No such file or directory: '/home/ucsddse230/work/Hello/Untitled.ipynb'
[NotebookApp | WARNING] Unexpected error while saving file: Hello/Untitled.ipynb [Errno 2] No such file or directory: '/home/ucsddse230/work/Hello/Untitled.ipynb'
[NotebookApp | ERROR] {
      "Host": "localhost:8889",
      "Connection": "keep-alive",
      "Content-Length": "1164",
      "Sec-Ch-Ua": "\"Not_A Brand\";v=\"99\", \"Google Chrome\";v=\"109\", \"Chromium\";v=\"109\"",
      "Sec-Ch-Ua-Mobile": "?0",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36",
      "Content-Type": "application/json",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|4e7bbeb5|6725ab6fc796ded8480ccbed5bb7e0f5|1675282490",
      "Sec-Ch-Ua-Platform": "\"Windows\"",
      "Origin": "http://localhost:8889",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:8889/notebooks/Hello/Untitled.ipynb?kernel_name=python3",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "fr-FR,fr;q=0.9,en-FR;q=0.8,en;q=0.7,en-US;q=0.6",
      "Cookie": "_xsrf=2|4e7bbeb5|6725ab6fc796ded8480ccbed5bb7e0f5|1675282490"
    }
[NotebookApp | ERROR] 500 PUT /api/contents/Hello/Untitled.ipynb (172.17.0.1) 36.48ms referer=http://localhost:8889/notebooks/Hello/Untitled.ipynb?kernel_name=python3
[NotebookApp | INFO] Kernel started: e48152ec-d164-4e22-8461-705ec0b9080e
[NotebookApp | WARNING] 404 GET /static/components/bootstrap/js/tooltip.js?v=20230201210718 (172.17.0.1) 5.87ms referer=http://localhost:8889/notebooks/Test%20Jupyter%20Notebook.ipynb
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel e48152ec-d164-4e22-8461-705ec0b9080e
[NotebookApp | INFO] interrupted
[NotebookApp | CRITICAL] received signal 2, stopping
[NotebookApp | INFO] Shutting down 1 kernel
[NotebookApp | INFO] Kernel shutdown: e48152ec-d164-4e22-8461-705ec0b9080e
[NotebookApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] Serving notebooks from local directory: /home/ucsddse230/work
[NotebookApp | INFO] 0 active kernels
[NotebookApp | INFO] The Jupyter Notebook is running at:
[NotebookApp | INFO] http://[all ip addresses on your system]:8888/
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | INFO] 302 GET / (172.17.0.1) 1.48ms
[NotebookApp | WARNING] Notebook Test Jupyter Notebook.ipynb is not trusted
[NotebookApp | INFO] Kernel started: 8beefd63-bebe-43f2-bb60-ff00e4e9acec
[NotebookApp | WARNING] 404 GET /static/components/bootstrap/js/tooltip.js?v=20230202065706 (172.17.0.1) 78.80ms referer=http://localhost:8889/notebooks/Test%20Jupyter%20Notebook.ipynb
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel 8beefd63-bebe-43f2-bb60-ff00e4e9acec
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | WARNING] Notebook Test Jupyter Notebook.ipynb is not trusted
[NotebookApp | WARNING] WebSocket ping timeout after 95714 ms.
[NotebookApp | INFO] Starting buffering for 8beefd63-bebe-43f2-bb60-ff00e4e9acec:611668280f384af68a3ca18ac096d2c0
[NotebookApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] Serving notebooks from local directory: /home/ucsddse230/work
[NotebookApp | INFO] 0 active kernels
[NotebookApp | INFO] The Jupyter Notebook is running at:
[NotebookApp | INFO] http://[all ip addresses on your system]:8888/
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | INFO] 302 GET / (172.17.0.1) 1.27ms
[NotebookApp | INFO] interrupted
[NotebookApp | CRITICAL] received signal 2, stopping
[NotebookApp | CRITICAL] received signal 2, stopping
[NotebookApp | CRITICAL] received signal 2, stopping
[NotebookApp | CRITICAL] received signal 2, stopping
[NotebookApp | INFO] Shutting down 0 kernels
[NotebookApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] Serving notebooks from local directory: /home/ucsddse230/work
[NotebookApp | INFO] 0 active kernels
[NotebookApp | INFO] The Jupyter Notebook is running at:
[NotebookApp | INFO] http://[all ip addresses on your system]:8888/
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | INFO] 302 GET / (172.17.0.1) 11.65ms
[NotebookApp | INFO] Writing notebook-signing key to /home/ucsddse230/.local/share/jupyter/notebook_secret
[NotebookApp | WARNING] Notebook Test Jupyter Notebook.ipynb is not trusted
[NotebookApp | INFO] Kernel started: 8f5d8ff5-a5ba-4bf5-acf0-ed6f66a1b22c
[NotebookApp | WARNING] 404 GET /static/components/bootstrap/js/tooltip.js?v=20230202072644 (172.17.0.1) 90.95ms referer=http://localhost:8889/notebooks/Test%20Jupyter%20Notebook.ipynb
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel 8f5d8ff5-a5ba-4bf5-acf0-ed6f66a1b22c
[NotebookApp | INFO] Starting buffering for 8f5d8ff5-a5ba-4bf5-acf0-ed6f66a1b22c:f3b9259195eb4e9d881de27680072b7b
[NotebookApp | INFO] Kernel restarted: 8f5d8ff5-a5ba-4bf5-acf0-ed6f66a1b22c
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel 8f5d8ff5-a5ba-4bf5-acf0-ed6f66a1b22c
[NotebookApp | INFO] Restoring connection for 8f5d8ff5-a5ba-4bf5-acf0-ed6f66a1b22c:f3b9259195eb4e9d881de27680072b7b
[NotebookApp | INFO] Replaying 6 buffered messages
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Starting buffering for 8f5d8ff5-a5ba-4bf5-acf0-ed6f66a1b22c:f3b9259195eb4e9d881de27680072b7b
[NotebookApp | INFO] Kernel restarted: 8f5d8ff5-a5ba-4bf5-acf0-ed6f66a1b22c
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel 8f5d8ff5-a5ba-4bf5-acf0-ed6f66a1b22c
[NotebookApp | INFO] Restoring connection for 8f5d8ff5-a5ba-4bf5-acf0-ed6f66a1b22c:f3b9259195eb4e9d881de27680072b7b
[NotebookApp | INFO] Replaying 6 buffered messages
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Starting buffering for 8f5d8ff5-a5ba-4bf5-acf0-ed6f66a1b22c:f3b9259195eb4e9d881de27680072b7b
[NotebookApp | INFO] Kernel restarted: 8f5d8ff5-a5ba-4bf5-acf0-ed6f66a1b22c
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel 8f5d8ff5-a5ba-4bf5-acf0-ed6f66a1b22c
[NotebookApp | INFO] Restoring connection for 8f5d8ff5-a5ba-4bf5-acf0-ed6f66a1b22c:f3b9259195eb4e9d881de27680072b7b
[NotebookApp | INFO] Replaying 6 buffered messages
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Starting buffering for 8f5d8ff5-a5ba-4bf5-acf0-ed6f66a1b22c:f3b9259195eb4e9d881de27680072b7b
[NotebookApp | INFO] Kernel restarted: 8f5d8ff5-a5ba-4bf5-acf0-ed6f66a1b22c
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel 8f5d8ff5-a5ba-4bf5-acf0-ed6f66a1b22c
[NotebookApp | INFO] Restoring connection for 8f5d8ff5-a5ba-4bf5-acf0-ed6f66a1b22c:f3b9259195eb4e9d881de27680072b7b
[NotebookApp | INFO] Replaying 3 buffered messages
[NotebookApp | INFO] Kernel shutdown: 8f5d8ff5-a5ba-4bf5-acf0-ed6f66a1b22c
[NotebookApp | INFO] Kernel started: 3e5900a5-89e0-4407-bcca-648244101bd9
[NotebookApp | WARNING] 404 GET /static/components/bootstrap/js/tooltip.js?v=20230202072644 (172.17.0.1) 13.85ms referer=http://localhost:8889/notebooks/Test%20Jupyter%20Notebook.ipynb
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel 3e5900a5-89e0-4407-bcca-648244101bd9
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Kernel shutdown: 3e5900a5-89e0-4407-bcca-648244101bd9
[NotebookApp | WARNING] 404 DELETE /api/sessions/832e839c-6bd1-4cc4-89ac-a5fbf61eccad (172.17.0.1): Session not found: session_id='832e839c-6bd1-4cc4-89ac-a5fbf61eccad'
[NotebookApp | WARNING] Session not found: session_id='832e839c-6bd1-4cc4-89ac-a5fbf61eccad'
[NotebookApp | WARNING] 404 DELETE /api/sessions/832e839c-6bd1-4cc4-89ac-a5fbf61eccad (172.17.0.1) 8.90ms referer=http://localhost:8889/tree?
[NotebookApp | INFO] interrupted
[NotebookApp | CRITICAL] received signal 2, stopping
[NotebookApp | INFO] Shutting down 0 kernels
[NotebookApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] Serving notebooks from local directory: /home/ucsddse230/work
[NotebookApp | INFO] 0 active kernels
[NotebookApp | INFO] The Jupyter Notebook is running at:
[NotebookApp | INFO] http://[all ip addresses on your system]:8888/
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | WARNING] 404 GET /api/kernels/3e5900a5-89e0-4407-bcca-648244101bd9/channels?session_id=7286da005f174c2196a13801bf4a7eec (172.17.0.1): Kernel does not exist: 3e5900a5-89e0-4407-bcca-648244101bd9
[NotebookApp | WARNING] 404 GET /api/kernels/3e5900a5-89e0-4407-bcca-648244101bd9/channels?session_id=7286da005f174c2196a13801bf4a7eec (172.17.0.1) 98.18ms referer=None
[NotebookApp | INFO] Kernel started: f2285b85-bac2-4fd3-b7b2-cdcf6247ea52
[NotebookApp | WARNING] 404 GET /static/components/bootstrap/js/tooltip.js?v=20230202153412 (172.17.0.1) 5.25ms referer=http://localhost:8889/notebooks/Test%20Jupyter%20Notebook.ipynb
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel f2285b85-bac2-4fd3-b7b2-cdcf6247ea52
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Saving file at /Test Jupyter Notebook.ipynb
[NotebookApp | INFO] Kernel shutdown: f2285b85-bac2-4fd3-b7b2-cdcf6247ea52
[NotebookApp | ERROR] Exception restarting kernel
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 85, in post
        yield gen.maybe_future(km.restart_kernel(kernel_id))
      File "/opt/conda/lib/python3.6/site-packages/notebook/services/kernels/kernelmanager.py", line 271, in restart_kernel
        self._check_kernel_id(kernel_id)
      File "/opt/conda/lib/python3.6/site-packages/notebook/services/kernels/kernelmanager.py", line 350, in _check_kernel_id
        raise web.HTTPError(404, u'Kernel does not exist: %s' % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: f2285b85-bac2-4fd3-b7b2-cdcf6247ea52)
[NotebookApp | ERROR] {
      "Host": "localhost:8889",
      "Connection": "keep-alive",
      "Content-Length": "0",
      "Sec-Ch-Ua": "\"Not_A Brand\";v=\"99\", \"Google Chrome\";v=\"109\", \"Chromium\";v=\"109\"",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|4e7bbeb5|6725ab6fc796ded8480ccbed5bb7e0f5|1675282490",
      "Sec-Ch-Ua-Mobile": "?0",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36",
      "Sec-Ch-Ua-Platform": "\"Windows\"",
      "Origin": "http://localhost:8889",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:8889/notebooks/Test%20Jupyter%20Notebook.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "fr-FR,fr;q=0.9,en-FR;q=0.8,en;q=0.7,en-US;q=0.6",
      "Cookie": "_xsrf=2|4e7bbeb5|6725ab6fc796ded8480ccbed5bb7e0f5|1675282490"
    }
[NotebookApp | ERROR] 500 POST /api/kernels/f2285b85-bac2-4fd3-b7b2-cdcf6247ea52/restart (172.17.0.1) 19.00ms referer=http://localhost:8889/notebooks/Test%20Jupyter%20Notebook.ipynb
[NotebookApp | WARNING] 404 DELETE /api/sessions/afb8f64b-3c40-41b1-bb8e-bdd8bacfdf4f (172.17.0.1): Session not found: session_id='afb8f64b-3c40-41b1-bb8e-bdd8bacfdf4f'
[NotebookApp | WARNING] Session not found: session_id='afb8f64b-3c40-41b1-bb8e-bdd8bacfdf4f'
[NotebookApp | WARNING] 404 DELETE /api/sessions/afb8f64b-3c40-41b1-bb8e-bdd8bacfdf4f (172.17.0.1) 17.36ms referer=http://localhost:8889/notebooks/Test%20Jupyter%20Notebook.ipynb
[NotebookApp | INFO] Kernel started: 151b686a-df7a-45fe-a5b1-a9b56a067766
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel 151b686a-df7a-45fe-a5b1-a9b56a067766
[NotebookApp | INFO] Starting buffering for 151b686a-df7a-45fe-a5b1-a9b56a067766:07bf0fb793f7416b9d047827a8172d9d
[NotebookApp | INFO] Kernel shutdown: 151b686a-df7a-45fe-a5b1-a9b56a067766
[NotebookApp | INFO] interrupted
[NotebookApp | CRITICAL] received signal 2, stopping
[NotebookApp | INFO] Shutting down 0 kernels
